# Generated by Django 2.1.5 on 2019-03-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0014_auto_20190302_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
