# Generated by Django 2.1.5 on 2019-03-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0016_auto_20190307_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='featured_post_image',
            field=models.ImageField(blank=True, help_text='Add Image if this is a featured post ', null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Your Company Logo', null=True, upload_to='logo'),
        ),
    ]
