# Generated by Django 2.1.5 on 2019-02-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('job_type', models.CharField(choices=[('part-time', 'Part Time'), ('full-time', 'Full Time'), ('internship', 'Internship')], max_length=200)),
                ('post_type', models.CharField(choices=[('featured', 'FEATURED'), ('standard', 'STANDARD')], max_length=200)),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('validity', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, help_text='top left image', null=True, upload_to='logo')),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Slug will be generated automatically from the title_2 of the post', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.Category')),
            ],
            options={
                'verbose_name_plural': 'Job Post',
            },
        ),
    ]
