# Generated by Django 2.1.5 on 2019-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_compnay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
