# Generated by Django 2.1.5 on 2019-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0010_auto_20190226_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='total_applied',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
