# Generated by Django 2.1.5 on 2019-02-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_freelancer',
        ),
    ]
