# Generated by Django 2.1.5 on 2019-02-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20190221_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
